{"result": "pass", "start_at": "2015-02-27 16:38:01.724125", "name": "PIMTest.testCalendarEvent", "end_at": "2015-02-27 16:38:32.339667"}
{"result": "pass", "start_at": "2015-02-27 16:38:32.340837", "name": "PIMTest.testClock", "end_at": "2015-02-27 16:39:02.525885"}
{"result": "pass", "start_at": "2015-03-10 14:38:12.476509", "name": "LauncherTest.testScreenLockUnlock", "end_at": "2015-03-10 14:38:26.980091"}
{"result": "fail", "start_at": "2015-03-10 15:03:55.691376", "log": "report/2015-03-10_15:03:55.690131/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:03:55.691376/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 55, in testSendMMSWithVideo\n    assert d(packageName = 'com.android.gallery3d').wait.exists(timeout = 5000),'Switch to gallery view failed in 5s!'\n", "AssertionError: Switch to gallery view failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-10_15:03:55.690131/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:03:55.691376/failure.png", "end_at": "2015-03-10 15:04:28.686192", "expect": null, "name": "MessageTest.testSendMMSWithVideo"}
{"result": "fail", "start_at": "2015-03-10 15:04:31.773797", "log": "report/2015-03-10_15:04:31.772603/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:04:31.773797/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 59, in testSendMMSWithVideo\n    d.click('MMS_Into_RootDir.png')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 218, in click\n    self.__click_image(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 249, in __click_image\n    raise ExpectException(expect_image_path, current_image_path, reason)\n", "ExpectException: \"Fail Reason: The wanted image 'MMS_Into_RootDir.png' not found on screen!\"\n"], "screenshot_at_failure": "report/2015-03-10_15:04:31.772603/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:04:31.773797/MMS_Into_RootDir.png", "end_at": "2015-03-10 15:05:00.769219", "expect": "report/2015-03-10_15:04:31.772603/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:04:31.773797/MMS_Into_RootDir_expect.png", "name": "MessageTest.testSendMMSWithVideo"}
{"result": "fail", "start_at": "2015-03-10 15:05:16.581726", "log": "report/2015-03-10_15:05:16.580498/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:05:16.581726/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 59, in testSendMMSWithVideo\n    d.click('MMS_Into_RootDir.png')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 218, in click\n    self.__click_image(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 249, in __click_image\n    raise ExpectException(expect_image_path, current_image_path, reason)\n", "ExpectException: \"Fail Reason: The wanted image 'MMS_Into_RootDir.png' not found on screen!\"\n"], "screenshot_at_failure": "report/2015-03-10_15:05:16.580498/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:05:16.581726/MMS_Into_RootDir.png", "end_at": "2015-03-10 15:05:46.162983", "expect": "report/2015-03-10_15:05:16.580498/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:05:16.581726/MMS_Into_RootDir_expect.png", "name": "MessageTest.testSendMMSWithVideo"}
{"result": "fail", "start_at": "2015-03-10 15:27:31.255931", "log": "report/2015-03-10_15:27:31.254707/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:27:31.255931/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 44, in testSendMMSWithVideo\n    self._launchAndEnterNewMsg()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 137, in _launchAndEnterNewMsg\n    assert d(description='\u53d1\u9001').wait.exists(timeout=5000), 'Can not switch to new message screen. '\n", "AssertionError: Can not switch to new message screen. \n"], "screenshot_at_failure": "report/2015-03-10_15:27:31.254707/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:27:31.255931/failure.png", "end_at": "2015-03-10 15:27:51.591980", "expect": null, "name": "MessageTest.testSendMMSWithVideo"}
{"result": "fail", "start_at": "2015-03-10 15:27:56.364804", "log": "report/2015-03-10_15:27:56.363618/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:27:56.364804/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 59, in testSendMMSWithVideo\n    d.click('MMS_Into_RootDir.png')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 218, in click\n    self.__click_image(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 249, in __click_image\n    raise ExpectException(expect_image_path, current_image_path, reason)\n", "ExpectException: \"Fail Reason: The wanted image 'MMS_Into_RootDir.png' not found on screen!\"\n"], "screenshot_at_failure": "report/2015-03-10_15:27:56.363618/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:27:56.364804/MMS_Into_RootDir.png", "end_at": "2015-03-10 15:28:26.139511", "expect": "report/2015-03-10_15:27:56.363618/fail/MessageTest.testSendMMSWithVideo@2015-03-10_15:27:56.364804/MMS_Into_RootDir_expect.png", "name": "MessageTest.testSendMMSWithVideo"}
{"result": "fail", "start_at": "2015-03-10 15:28:29.841767", "log": "report/2015-03-10_15:27:56.363618/fail/MessageTest.testSendMMSWithPics@2015-03-10_15:28:29.841767/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 84, in testSendMMSWithPics\n    d.click('MMS_Into_RootDir.png')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 218, in click\n    self.__click_image(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 249, in __click_image\n    raise ExpectException(expect_image_path, current_image_path, reason)\n", "ExpectException: \"Fail Reason: The wanted image 'MMS_Into_RootDir.png' not found on screen!\"\n"], "screenshot_at_failure": "report/2015-03-10_15:27:56.363618/fail/MessageTest.testSendMMSWithPics@2015-03-10_15:28:29.841767/MMS_Into_RootDir.png", "end_at": "2015-03-10 15:29:12.011764", "expect": "report/2015-03-10_15:27:56.363618/fail/MessageTest.testSendMMSWithPics@2015-03-10_15:28:29.841767/MMS_Into_RootDir_expect.png", "name": "MessageTest.testSendMMSWithPics"}
{"result": "pass", "start_at": "2015-03-10 15:31:08.509886", "name": "MessageTest.testSendMMSWithVideo", "end_at": "2015-03-10 15:32:00.122944"}
{"result": "pass", "start_at": "2015-03-10 15:32:00.124215", "name": "MessageTest.testSendMMSWithPics", "end_at": "2015-03-10 15:32:45.283981"}
{"result": "pass", "start_at": "2015-03-10 15:32:45.285044", "name": "MessageTest.testSendMMSWithPics", "end_at": "2015-03-10 15:33:29.963706"}
{"result": "fail", "start_at": "2015-03-12 19:44:27.475802", "log": "report/2015-03-12_19:44:27.466610/fail/The3rdTest.testYouku@2015-03-12_19:44:27.475802/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 123, in testYouku\n    assert d(packageName = 'com.youku.phone').wait.exists(timeout = 5000),'Launch Youku failed in 5s!'\n", "AssertionError: Launch Youku failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-12_19:44:27.466610/fail/The3rdTest.testYouku@2015-03-12_19:44:27.475802/failure.png", "end_at": "2015-03-12 19:44:47.665041", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "fail", "start_at": "2015-03-12 19:44:51.408539", "log": "report/2015-03-12_19:44:27.466610/fail/The3rdTest.testYouku@2015-03-12_19:44:51.408539/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 123, in testYouku\n    assert d(packageName = 'com.youku.phone').wait.exists(timeout = 5000),'Launch Youku failed in 5s!'\n", "AssertionError: Launch Youku failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-12_19:44:27.466610/fail/The3rdTest.testYouku@2015-03-12_19:44:51.408539/failure.png", "end_at": "2015-03-12 19:45:06.248110", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 19:47:07.851720", "log": "report/2015-03-12_19:47:07.557684/error/EmailTest.testReadEmailWithAtt@2015-03-12_19:47:07.851720/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/email.py\", line 143, in testReadEmailWithAtt\n    d(text = '\u5df2\u52a0\u661f\u6807').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[TEXT=\\u5df2\\u52a0\\u661f\\u6807]\n"], "screenshot_at_failure": "report/2015-03-12_19:47:07.557684/error/EmailTest.testReadEmailWithAtt@2015-03-12_19:47:07.851720/failure.png", "end_at": "2015-03-12 19:47:46.871876", "expect": null, "name": "EmailTest.testReadEmailWithAtt"}
{"result": "error", "start_at": "2015-03-12 19:47:50.639312", "log": "report/2015-03-12_19:47:07.557684/error/EmailTest.testReadEmailWithAtt@2015-03-12_19:47:50.639312/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/email.py\", line 143, in testReadEmailWithAtt\n    d(text = '\u5df2\u52a0\u661f\u6807').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[TEXT=\\u5df2\\u52a0\\u661f\\u6807]\n"], "screenshot_at_failure": "report/2015-03-12_19:47:07.557684/error/EmailTest.testReadEmailWithAtt@2015-03-12_19:47:50.639312/failure.png", "end_at": "2015-03-12 19:48:25.557956", "expect": null, "name": "EmailTest.testReadEmailWithAtt"}
{"result": "fail", "start_at": "2015-03-12 19:52:34.133036", "log": "report/2015-03-12_19:52:33.840028/fail/EmailTest.testReadEmailWithAtt@2015-03-12_19:52:34.133036/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/email.py\", line 159, in testReadEmailWithAtt\n    assert d(text = '\u6253\u5f00').wait.exists(timeout = 10000),'Download attachment failed in 10s!'\n", "AssertionError: Download attachment failed in 10s!\n"], "screenshot_at_failure": "report/2015-03-12_19:52:33.840028/fail/EmailTest.testReadEmailWithAtt@2015-03-12_19:52:34.133036/failure.png", "end_at": "2015-03-12 19:53:08.965914", "expect": null, "name": "EmailTest.testReadEmailWithAtt"}
{"result": "pass", "start_at": "2015-03-12 19:54:54.966715", "name": "EmailTest.testReadEmailWithAtt", "end_at": "2015-03-12 19:55:20.669593"}
{"result": "error", "start_at": "2015-03-12 20:14:42.584511", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:42.584511/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:42.584511/failure.png", "end_at": "2015-03-12 20:14:53.610137", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:14:53.613530", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:53.613530/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:53.613530/failure.png", "end_at": "2015-03-12 20:14:56.394512", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:14:56.396313", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:56.396313/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:56.396313/failure.png", "end_at": "2015-03-12 20:14:56.892763", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:14:56.893581", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:56.893581/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:56.893581/failure.png", "end_at": "2015-03-12 20:14:57.016849", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:14:57.018800", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.018800/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.018800/failure.png", "end_at": "2015-03-12 20:14:57.140059", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:14:57.141870", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.141870/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.141870/failure.png", "end_at": "2015-03-12 20:14:57.265032", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:14:57.266789", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.266789/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.266789/failure.png", "end_at": "2015-03-12 20:14:57.388213", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:14:57.389934", "log": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.389934/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 10, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 281, in device_serial\n    raise EnvironmentError(\"Multiple devices attached but default android serial not set.\")\n", "EnvironmentError: Multiple devices attached but default android serial not set.\n"], "screenshot_at_failure": "report/2015-03-12_20:14:42.577766/error/The3rdTest.testYouku@2015-03-12_20:14:57.389934/failure.png", "end_at": "2015-03-12 20:14:57.513233", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "fail", "start_at": "2015-03-12 20:15:49.305158", "log": "report/2015-03-12_20:15:49.296092/fail/The3rdTest.testYouku@2015-03-12_20:15:49.305158/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 125, in testYouku\n    assert d(resourceId = 'com.youku.phone:id/homepage_gallery_item_play').wait.exists(timeout = 10000),'Youku homepage does not loading finished in 10s!'\n", "AssertionError: Youku homepage does not loading finished in 10s!\n"], "screenshot_at_failure": "report/2015-03-12_20:15:49.296092/fail/The3rdTest.testYouku@2015-03-12_20:15:49.305158/failure.png", "end_at": "2015-03-12 20:16:15.493694", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-12 20:18:59.425293", "log": "report/2015-03-12_20:18:59.417790/error/The3rdTest.testYouku@2015-03-12_20:18:59.425293/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 128, in testYouku\n    d(resourceId = 'com.youku.phone:id/homepage_gallery_item_play').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[RESOURCE_ID=com.youku.phone:id/homepage_gallery_item_play]\n"], "screenshot_at_failure": "report/2015-03-12_20:18:59.417790/error/The3rdTest.testYouku@2015-03-12_20:18:59.425293/failure.png", "end_at": "2015-03-12 20:19:43.331902", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "fail", "start_at": "2015-03-12 20:21:56.494905", "log": "report/2015-03-12_20:21:56.487574/fail/The3rdTest.testYouku@2015-03-12_20:21:56.494905/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 130, in testYouku\n    assert d(textContains = '\u7f13\u5b58').wait.exists(timeout = 5000),'Switch surface view failed in 5s!'\n", "AssertionError: Switch surface view failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-12_20:21:56.487574/fail/The3rdTest.testYouku@2015-03-12_20:21:56.494905/failure.png", "end_at": "2015-03-12 20:22:33.864962", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "fail", "start_at": "2015-03-12 20:25:46.044795", "log": "report/2015-03-12_20:25:46.037248/fail/The3rdTest.testYouku@2015-03-12_20:25:46.044795/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 125, in testYouku\n    assert d(resourceId = 'com.youku.phone:id/home_gallery_item_title_layout').wait.exists(timeout = 10000),'Youku homepage does not loading finished in 10s!'\n", "AssertionError: Youku homepage does not loading finished in 10s!\n"], "screenshot_at_failure": "report/2015-03-12_20:25:46.037248/fail/The3rdTest.testYouku@2015-03-12_20:25:46.044795/failure.png", "end_at": "2015-03-12 20:26:09.476831", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "pass", "start_at": "2015-03-12 20:26:13.927814", "name": "The3rdTest.testYouku", "end_at": "2015-03-12 20:26:46.592433"}
{"result": "pass", "start_at": "2015-03-16 11:33:29.815653", "name": "SettingTest.testTurnOnOffBT", "end_at": "2015-03-16 11:33:52.787702"}
{"result": "error", "start_at": "2015-03-16 11:33:52.811272", "log": "report/2015-03-16_11:33:29.774754/error/SettingTest.testTurnOnOffNFC@2015-03-16_11:33:52.811272/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/setting.py\", line 86, in testTurnOnOffNFC\n    .swipe.right(steps = 5)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 908, in _swipe\n    return self.jsonrpc.swipe(self.selector, direction, steps)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[CHILD=UiSelector[CLASS=smartisanos.widget.SwitchEx], CONTAINER=UiSelector[CLASS=android.widget.RelativeLayout, RESOURCE_ID=com.android.settings:id/item_id_nfc], PATTERN=UiSelector[INSTANCE=0, PATTERN=UiSelector[CLASS=android.widget.TextView]]]\n"], "screenshot_at_failure": "report/2015-03-16_11:33:29.774754/error/SettingTest.testTurnOnOffNFC@2015-03-16_11:33:52.811272/failure.png", "end_at": "2015-03-16 11:34:30.922169", "expect": null, "name": "SettingTest.testTurnOnOffNFC"}
{"result": "pass", "start_at": "2015-03-16 13:17:46.997010", "name": "SettingTest.testTurnOnOffBT", "end_at": "2015-03-16 13:18:11.330055"}
{"result": "error", "start_at": "2015-03-16 13:18:11.331304", "log": "report/2015-03-16_13:17:46.994541/error/SettingTest.testTurnOnOffNFC@2015-03-16_13:18:11.331304/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/setting.py\", line 83, in testTurnOnOffNFC\n    d(text=\"NFC\").right(className=\"smartisanos.widget.SwitchEx\").swipe.right(steps = 5)\n", "AttributeError: 'NoneType' object has no attribute 'swipe'\n"], "screenshot_at_failure": "report/2015-03-16_13:17:46.994541/error/SettingTest.testTurnOnOffNFC@2015-03-16_13:18:11.331304/failure.png", "end_at": "2015-03-16 13:18:25.734360", "expect": null, "name": "SettingTest.testTurnOnOffNFC"}
{"result": "pass", "start_at": "2015-03-16 13:19:17.501171", "name": "SettingTest.testTurnOnOffBT", "end_at": "2015-03-16 13:19:37.674790"}
{"result": "error", "start_at": "2015-03-16 13:19:37.676037", "log": "report/2015-03-16_13:19:17.499379/error/SettingTest.testTurnOnOffNFC@2015-03-16_13:19:37.676037/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/setting.py\", line 83, in testTurnOnOffNFC\n    d(text=\"NFC\").right(className=\"smartisanos.widget.SwitchEx\").click()\n", "AttributeError: 'NoneType' object has no attribute 'click'\n"], "screenshot_at_failure": "report/2015-03-16_13:19:17.499379/error/SettingTest.testTurnOnOffNFC@2015-03-16_13:19:37.676037/failure.png", "end_at": "2015-03-16 13:19:52.294503", "expect": null, "name": "SettingTest.testTurnOnOffNFC"}
{"result": "pass", "start_at": "2015-03-16 13:27:30.204852", "name": "SettingTest.testTurnOnOffBT", "end_at": "2015-03-16 13:27:53.219956"}
{"result": "pass", "start_at": "2015-03-16 13:27:53.221182", "name": "SettingTest.testTurnOnOffNFC", "end_at": "2015-03-16 13:28:09.460022"}
{"result": "pass", "start_at": "2015-03-16 13:31:22.192046", "name": "SettingTest.testTurnOnOffNFC", "end_at": "2015-03-16 13:31:39.612673"}
{"result": "fail", "start_at": "2015-03-16 13:31:54.354397", "log": "report/2015-03-16_13:31:54.352604/fail/SettingTest.testTurnOnOffNFC@2015-03-16_13:31:54.354397/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/setting.py\", line 84, in testTurnOnOffNFC\n    assert d(className=\"android.widget.RelativeLayout\", resourceId=\"com.android.settings:id/item_id_android_beam\").child(className=\"smartisanos.widget.SwitchEx\").enabled,'Turn NFC failed in 5s!'\n", "AssertionError: Turn NFC failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-16_13:31:54.352604/fail/SettingTest.testTurnOnOffNFC@2015-03-16_13:31:54.354397/failure.png", "end_at": "2015-03-16 13:32:08.636120", "expect": null, "name": "SettingTest.testTurnOnOffNFC"}
{"result": "fail", "start_at": "2015-03-16 13:32:35.332551", "log": "report/2015-03-16_13:32:35.330695/fail/SettingTest.testTurnOnOffNFC@2015-03-16_13:32:35.332551/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/setting.py\", line 84, in testTurnOnOffNFC\n    assert d(className=\"android.widget.RelativeLayout\", resourceId=\"com.android.settings:id/item_id_android_beam\").child(className=\"smartisanos.widget.SwitchEx\").enabled,'Turn NFC failed!'\n", "AssertionError: Turn NFC failed!\n"], "screenshot_at_failure": "report/2015-03-16_13:32:35.330695/fail/SettingTest.testTurnOnOffNFC@2015-03-16_13:32:35.332551/failure.png", "end_at": "2015-03-16 13:32:49.900767", "expect": null, "name": "SettingTest.testTurnOnOffNFC"}
{"result": "fail", "start_at": "2015-03-16 13:36:51.854538", "log": "report/2015-03-16_13:36:51.852748/fail/SettingTest.testTurnOnOffNFC@2015-03-16_13:36:51.854538/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/setting.py\", line 84, in testTurnOnOffNFC\n    assert d(className=\"android.widget.RelativeLayout\", resourceId=\"com.android.settings:id/item_id_android_beam\").child(className=\"smartisanos.widget.SwitchEx\").info['enabled'],'Turn NFC failed!'\n", "AssertionError: Turn NFC failed!\n"], "screenshot_at_failure": "report/2015-03-16_13:36:51.852748/fail/SettingTest.testTurnOnOffNFC@2015-03-16_13:36:51.854538/failure.png", "end_at": "2015-03-16 13:37:06.044705", "expect": null, "name": "SettingTest.testTurnOnOffNFC"}
{"result": "pass", "start_at": "2015-03-16 13:38:25.128337", "name": "SettingTest.testTurnOnOffNFC", "end_at": "2015-03-16 13:38:45.862731"}
{"result": "pass", "start_at": "2015-03-16 13:38:48.110068", "name": "SettingTest.testTurnOnOffNFC", "end_at": "2015-03-16 13:39:09.363562"}
{"result": "pass", "start_at": "2015-03-16 13:39:11.945709", "name": "SettingTest.testTurnOnOffNFC", "end_at": "2015-03-16 13:39:33.169552"}
{"result": "pass", "start_at": "2015-03-16 13:39:36.304063", "name": "SettingTest.testTurnOnOffNFC", "end_at": "2015-03-16 13:39:57.197691"}
{"result": "error", "start_at": "2015-03-16 13:40:24.686674", "log": "report/2015-03-16_13:40:24.684638/error/SettingTest.testTurnOnOffNFC@2015-03-16_13:40:24.686674/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/setting.py\", line 85, in testTurnOnOffNFC\n    assert d(className=\"android.widget.RelativeLayout\", resourceId=\"com.android.settings:id/item_id_android_beam\").child(className=\"smartisanos.widget.SwitchEx\").info['enabled'](timeout = 5000),'Turn NFC failed!'\n", "TypeError: 'bool' object is not callable\n"], "screenshot_at_failure": "report/2015-03-16_13:40:24.684638/error/SettingTest.testTurnOnOffNFC@2015-03-16_13:40:24.686674/failure.png", "end_at": "2015-03-16 13:40:39.488411", "expect": null, "name": "SettingTest.testTurnOnOffNFC"}
{"result": "pass", "start_at": "2015-03-16 13:41:37.925128", "name": "SettingTest.testTurnOnOffNFC", "end_at": "2015-03-16 13:41:58.647048"}
{"result": "fail", "start_at": "2015-03-16 14:07:21.237891", "log": "report/2015-03-16_14:07:21.209759/fail/The3rdTest.testNavigation@2015-03-16_14:07:21.237891/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 69, in testNavigation\n    assert d(packageName = 'com.autonavi.minimap').wait.exists(timeout = 5000),'Launch Navigation failed in 5s!'\n", "AssertionError: Launch Navigation failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-16_14:07:21.209759/fail/The3rdTest.testNavigation@2015-03-16_14:07:21.237891/failure.png", "end_at": "2015-03-16 14:07:42.090977", "expect": null, "name": "The3rdTest.testNavigation"}
{"result": "error", "start_at": "2015-03-16 14:09:06.595369", "log": "report/2015-03-16_14:09:06.593224/error/The3rdTest.testNavigation@2015-03-16_14:09:06.595369/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 77, in testNavigation\n    direction = random.choice(['left','right','up','down'])\n", "NameError: global name 'random' is not defined\n"], "screenshot_at_failure": "report/2015-03-16_14:09:06.593224/error/The3rdTest.testNavigation@2015-03-16_14:09:06.595369/failure.png", "end_at": "2015-03-16 14:09:17.889471", "expect": null, "name": "The3rdTest.testNavigation"}
{"result": "error", "start_at": "2015-03-16 14:09:38.389644", "log": "report/2015-03-16_14:09:38.387596/error/The3rdTest.testNavigation@2015-03-16_14:09:38.389644/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 80, in testNavigation\n    self._swipeScreen(direction,step)\n", "AttributeError: 'The3rdTest' object has no attribute '_swipeScreen'\n"], "screenshot_at_failure": "report/2015-03-16_14:09:38.387596/error/The3rdTest.testNavigation@2015-03-16_14:09:38.389644/failure.png", "end_at": "2015-03-16 14:09:49.430498", "expect": null, "name": "The3rdTest.testNavigation"}
{"result": "error", "start_at": "2015-03-16 14:10:08.988495", "log": "report/2015-03-16_14:10:08.986427/error/The3rdTest.testNavigation@2015-03-16_14:10:08.988495/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 89, in testNavigation\n    d(text = '\u786e\u5b9a').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[TEXT=\\u786e\\u5b9a]\n"], "screenshot_at_failure": "report/2015-03-16_14:10:08.986427/error/The3rdTest.testNavigation@2015-03-16_14:10:08.988495/failure.png", "end_at": "2015-03-16 14:11:24.262226", "expect": null, "name": "The3rdTest.testNavigation"}
{"result": "pass", "start_at": "2015-03-16 14:11:56.008548", "name": "The3rdTest.testNavigation", "end_at": "2015-03-16 14:12:40.662681"}
{"result": "error", "start_at": "2015-03-16 14:30:30.894371", "log": "report/2015-03-16_14:30:30.882712/error/BrowserTest.testVisitWebPage@2015-03-16_14:30:30.894371/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 356, in run\n    self.tearDown()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 16, in tearDown\n    self._clearCache()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 222, in _clearCache\n    d(resourceId = 'com.android.browser:id/option_list_item_text',text = '\u8bbe\u7f6e').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[TEXT=\\u8bbe\\u7f6e, RESOURCE_ID=com.android.browser:id/option_list_item_text]\n"], "screenshot_at_failure": "report/2015-03-16_14:30:30.882712/error/BrowserTest.testVisitWebPage@2015-03-16_14:30:30.894371/failure.png", "end_at": "2015-03-16 14:31:32.048442", "expect": null, "name": "BrowserTest.testVisitWebPage"}
{"result": "error", "start_at": "2015-03-16 14:40:35.323126", "log": "report/2015-03-16_14:40:35.320964/error/BrowserTest.testVisitWebPage@2015-03-16_14:40:35.323126/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 356, in run\n    self.tearDown()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 16, in tearDown\n    self._clearCache()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 223, in _clearCache\n    d.clikc(590,1700)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 61, in __getattr__\n    raise AttributeError(attr)\n", "AttributeError: clikc\n"], "screenshot_at_failure": "report/2015-03-16_14:40:35.320964/error/BrowserTest.testVisitWebPage@2015-03-16_14:40:35.323126/failure.png", "end_at": "2015-03-16 14:41:12.184488", "expect": null, "name": "BrowserTest.testVisitWebPage"}
{"result": "error", "start_at": "2015-03-16 14:41:42.968574", "log": "report/2015-03-16_14:41:42.966409/error/BrowserTest.testVisitWebPage@2015-03-16_14:41:42.968574/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 356, in run\n    self.tearDown()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 16, in tearDown\n    self._clearCache()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 224, in _clearCache\n    d.clikc(590,1700)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 61, in __getattr__\n    raise AttributeError(attr)\n", "AttributeError: clikc\n"], "screenshot_at_failure": "report/2015-03-16_14:41:42.966409/error/BrowserTest.testVisitWebPage@2015-03-16_14:41:42.968574/failure.png", "end_at": "2015-03-16 14:42:20.025682", "expect": null, "name": "BrowserTest.testVisitWebPage"}
{"result": "pass", "start_at": "2015-03-16 14:42:37.260705", "name": "BrowserTest.testVisitWebPage", "end_at": "2015-03-16 14:43:35.385300"}
{"result": "pass", "start_at": "2015-03-16 14:43:35.386550", "name": "BrowserTest.testVisitWebPage", "end_at": "2015-03-16 14:44:31.001172"}
{"result": "error", "start_at": "2015-03-16 15:57:42.128483", "log": "report/2015-03-16_15:57:42.126186/error/BrowserTest.testDownloadPics@2015-03-16_15:57:42.128483/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 13, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 277, in device_serial\n    raise EnvironmentError(\"Device %s not connected!\" % self.default_serial)\n", "EnvironmentError: Device 189889c3 not connected!\n"], "screenshot_at_failure": "report/2015-03-16_15:57:42.126186/error/BrowserTest.testDownloadPics@2015-03-16_15:57:42.128483/failure.png", "end_at": "2015-03-16 15:59:12.169990", "expect": null, "name": "BrowserTest.testDownloadPics"}
{"result": "error", "start_at": "2015-03-16 15:59:12.170863", "log": "report/2015-03-16_15:57:42.126186/error/BrowserTest.testDownloadAudio@2015-03-16_15:59:12.170863/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 13, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 277, in device_serial\n    raise EnvironmentError(\"Device %s not connected!\" % self.default_serial)\n", "EnvironmentError: Device 189889c3 not connected!\n"], "screenshot_at_failure": "report/2015-03-16_15:57:42.126186/error/BrowserTest.testDownloadAudio@2015-03-16_15:59:12.170863/failure.png", "end_at": "2015-03-16 15:59:25.394269", "expect": null, "name": "BrowserTest.testDownloadAudio"}
{"result": "error", "start_at": "2015-03-16 15:59:25.396256", "log": "report/2015-03-16_15:57:42.126186/error/BrowserTest.testDownloadVideo@2015-03-16_15:59:25.396256/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 318, in run\n    self.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 13, in setUp\n    u.setUp()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 32, in setUp\n    unlock()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/util.py\", line 20, in unlock\n    d.wakeup()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 57, in wrapper\n    return m(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 713, in wakeup\n    self.server.jsonrpc.wakeUp()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 400, in wrapper\n    server.start()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 428, in start\n    files = self.push()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 372, in push\n    self.adb.cmd(\"push\", filename, \"/data/local/tmp/\").wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 260, in cmd\n    cmd_line = [\"-s\", self.device_serial()] + list(args)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 277, in device_serial\n    raise EnvironmentError(\"Device %s not connected!\" % self.default_serial)\n", "EnvironmentError: Device 189889c3 not connected!\n"], "screenshot_at_failure": "report/2015-03-16_15:57:42.126186/error/BrowserTest.testDownloadVideo@2015-03-16_15:59:25.396256/failure.png", "end_at": "2015-03-16 15:59:26.826151", "expect": null, "name": "BrowserTest.testDownloadVideo"}
{"result": "pass", "start_at": "2015-03-16 16:00:03.100041", "name": "BrowserTest.testDownloadPics", "end_at": "2015-03-16 16:01:04.710487"}
{"result": "fail", "start_at": "2015-03-16 16:01:04.711875", "log": "report/2015-03-16_16:00:03.097651/fail/BrowserTest.testDownloadAudio@2015-03-16_16:01:04.711875/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 137, in testDownloadAudio\n    assert d(text = '\u662f\u5426\u4e0b\u8f7d\u8be5\u6587\u4ef6?').wait.exists(timeout = 10000), 'Not trigger download. '\n", "AssertionError: Not trigger download. \n"], "screenshot_at_failure": "report/2015-03-16_16:00:03.097651/fail/BrowserTest.testDownloadAudio@2015-03-16_16:01:04.711875/failure.png", "end_at": "2015-03-16 16:01:32.655575", "expect": null, "name": "BrowserTest.testDownloadAudio"}
{"result": "fail", "start_at": "2015-03-16 16:02:17.447933", "log": "report/2015-03-16_16:02:17.446763/fail/BrowserTest.testDownloadAudio@2015-03-16_16:02:17.447933/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 137, in testDownloadAudio\n    assert d(text = '\u662f\u5426\u4e0b\u8f7d\u8be5\u6587\u4ef6?').wait.exists(timeout = 10000), 'Not trigger download. '\n", "AssertionError: Not trigger download. \n"], "screenshot_at_failure": "report/2015-03-16_16:02:17.446763/fail/BrowserTest.testDownloadAudio@2015-03-16_16:02:17.447933/failure.png", "end_at": "2015-03-16 16:02:47.434697", "expect": null, "name": "BrowserTest.testDownloadAudio"}
{"result": "fail", "start_at": "2015-03-16 16:03:09.097004", "log": "report/2015-03-16_16:03:09.094485/fail/BrowserTest.testDownloadAudio@2015-03-16_16:03:09.097004/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 137, in testDownloadAudio\n    assert d(text = '\u662f\u5426\u4e0b\u8f7d\u8be5\u6587\u4ef6?').wait.exists(timeout = 10000), 'Not trigger download. '\n", "AssertionError: Not trigger download. \n"], "screenshot_at_failure": "report/2015-03-16_16:03:09.094485/fail/BrowserTest.testDownloadAudio@2015-03-16_16:03:09.097004/failure.png", "end_at": "2015-03-16 16:03:38.474488", "expect": null, "name": "BrowserTest.testDownloadAudio"}
{"result": "pass", "start_at": "2015-03-16 16:03:59.749940", "name": "BrowserTest.testDownloadAudio", "end_at": "2015-03-16 16:04:52.627046"}
{"result": "fail", "start_at": "2015-03-16 16:17:24.524567", "log": "report/2015-03-16_16:17:24.522327/fail/BrowserTest.testPlayStreamingVideo@2015-03-16_16:17:24.524567/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 210, in testPlayStreamingVideo\n    d.click('Streaming_Play.png')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 218, in click\n    self.__click_image(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 249, in __click_image\n    raise ExpectException(expect_image_path, current_image_path, reason)\n", "ExpectException: \"Fail Reason: The wanted image 'Streaming_Play.png' not found on screen!\"\n"], "screenshot_at_failure": "report/2015-03-16_16:17:24.522327/fail/BrowserTest.testPlayStreamingVideo@2015-03-16_16:17:24.524567/Streaming_Play.png", "end_at": "2015-03-16 16:17:49.819617", "expect": "report/2015-03-16_16:17:24.522327/fail/BrowserTest.testPlayStreamingVideo@2015-03-16_16:17:24.524567/Streaming_Play_expect.png", "name": "BrowserTest.testPlayStreamingVideo"}
{"result": "error", "start_at": "2015-03-16 16:20:49.260815", "log": "report/2015-03-16_16:20:49.258306/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:20:49.260815/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 356, in run\n    self.tearDown()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 16, in tearDown\n    self._clearCache()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 224, in _clearCache\n    d(resourceId = 'com.android.browser:id/clearall').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[RESOURCE_ID=com.android.browser:id/clearall]\n"], "screenshot_at_failure": "report/2015-03-16_16:20:49.258306/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:20:49.260815/failure.png", "end_at": "2015-03-16 16:21:59.587119", "expect": null, "name": "BrowserTest.testPlayStreamingVideo"}
{"result": "fail", "start_at": "2015-03-16 16:24:18.432618", "log": "report/2015-03-16_16:24:18.429947/fail/BrowserTest.testPlayStreamingVideo@2015-03-16_16:24:18.432618/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 212, in testPlayStreamingVideo\n    assert d(resourceId = 'android:id/mediacontroller_progress').wait.exists(timeout = 15000),'Loading streaming video failed in 15s!'\n", "AssertionError: Loading streaming video failed in 15s!\n"], "screenshot_at_failure": "report/2015-03-16_16:24:18.429947/fail/BrowserTest.testPlayStreamingVideo@2015-03-16_16:24:18.432618/failure.png", "end_at": "2015-03-16 16:25:02.092611", "expect": null, "name": "BrowserTest.testPlayStreamingVideo"}
{"result": "error", "start_at": "2015-03-16 16:24:18.432618", "log": "report/2015-03-16_16:24:18.429947/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:24:18.432618/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 356, in run\n    self.tearDown()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 16, in tearDown\n    self._clearCache()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 227, in _clearCache\n    d(resourceId = 'com.android.browser:id/clearall').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[RESOURCE_ID=com.android.browser:id/clearall]\n"], "screenshot_at_failure": "report/2015-03-16_16:24:18.429947/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:24:18.432618/failure.png", "end_at": "2015-03-16 16:25:29.342057", "expect": null, "name": "BrowserTest.testPlayStreamingVideo"}
{"result": "fail", "start_at": "2015-03-16 16:25:36.433354", "log": "report/2015-03-16_16:25:36.432263/fail/BrowserTest.testPlayStreamingVideo@2015-03-16_16:25:36.433354/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 212, in testPlayStreamingVideo\n    assert d(resourceId = 'android:id/mediacontroller_progress').wait.exists(timeout = 15000),'Loading streaming video failed in 15s!'\n", "AssertionError: Loading streaming video failed in 15s!\n"], "screenshot_at_failure": "report/2015-03-16_16:25:36.432263/fail/BrowserTest.testPlayStreamingVideo@2015-03-16_16:25:36.433354/failure.png", "end_at": "2015-03-16 16:26:19.835890", "expect": null, "name": "BrowserTest.testPlayStreamingVideo"}
{"result": "error", "start_at": "2015-03-16 16:35:10.956483", "log": "report/2015-03-16_16:35:10.954296/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:35:10.956483/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 356, in run\n    self.tearDown()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 16, in tearDown\n    self._clearCache()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 236, in _clearCache\n    assert d(text = '\u8bbe\u7f6e').wait.exists(timeout = 3000),'Switch to setting view failed in 3s!'\n", "AssertionError: Switch to setting view failed in 3s!\n"], "screenshot_at_failure": "report/2015-03-16_16:35:10.954296/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:35:10.956483/failure.png", "end_at": "2015-03-16 16:36:08.803655", "expect": null, "name": "BrowserTest.testPlayStreamingVideo"}
{"result": "error", "start_at": "2015-03-16 16:37:36.467538", "log": "report/2015-03-16_16:37:36.466441/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:37:36.467538/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 356, in run\n    self.tearDown()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 16, in tearDown\n    self._clearCache()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/browser.py\", line 236, in _clearCache\n    assert d(text = '\u8bbe\u7f6e').wait.exists(timeout = 3000),'Switch to setting view failed in 3s!'\n", "AssertionError: Switch to setting view failed in 3s!\n"], "screenshot_at_failure": "report/2015-03-16_16:37:36.466441/error/BrowserTest.testPlayStreamingVideo@2015-03-16_16:37:36.467538/failure.png", "end_at": "2015-03-16 16:38:33.114693", "expect": null, "name": "BrowserTest.testPlayStreamingVideo"}
{"result": "pass", "start_at": "2015-03-16 16:42:46.450479", "name": "BrowserTest.testPlayStreamingVideo", "end_at": "2015-03-16 16:43:59.814280"}
{"result": "pass", "start_at": "2015-03-31 11:21:44.624121", "name": "The3rdTest.testWeibo", "end_at": "2015-03-31 11:22:37.879833"}
{"result": "error", "start_at": "2015-03-31 11:22:37.905656", "log": "report/2015-03-31_11:21:44.594995/error/The3rdTest.testWeixin@2015-03-31_11:22:37.905656/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 64, in testWeixin\n    d(resourceId = 'com.tencent.mm:id/bhz').click()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 811, in _click\n    return self.jsonrpc.click(self.selector)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[RESOURCE_ID=com.tencent.mm:id/bhz]\n"], "screenshot_at_failure": "report/2015-03-31_11:21:44.594995/error/The3rdTest.testWeixin@2015-03-31_11:22:37.905656/failure.png", "end_at": "2015-03-31 11:23:24.685017", "expect": null, "name": "The3rdTest.testWeixin"}
{"result": "fail", "start_at": "2015-03-31 11:23:28.500866", "log": "report/2015-03-31_11:21:44.594995/fail/The3rdTest.testNavigation@2015-03-31_11:23:28.500866/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 70, in testNavigation\n    assert d(packageName = 'com.autonavi.minimap').wait.exists(timeout = 5000),'Launch Navigation failed in 5s!'\n", "AssertionError: Launch Navigation failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-31_11:21:44.594995/fail/The3rdTest.testNavigation@2015-03-31_11:23:28.500866/failure.png", "end_at": "2015-03-31 11:23:49.095507", "expect": null, "name": "The3rdTest.testNavigation"}
{"result": "error", "start_at": "2015-03-31 11:23:52.842589", "log": "report/2015-03-31_11:21:44.594995/error/The3rdTest.testGame@2015-03-31_11:23:52.842589/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 116, in testGame\n    self._swipeMap(direction,step)\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 164, in _swipeMap\n    d(resourceId = 'com.autonavi.minimap:id/right_content').swipe.right(steps=step)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 908, in _swipe\n    return self.jsonrpc.swipe(self.selector, direction, steps)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[RESOURCE_ID=com.autonavi.minimap:id/right_content]\n"], "screenshot_at_failure": "report/2015-03-31_11:21:44.594995/error/The3rdTest.testGame@2015-03-31_11:23:52.842589/failure.png", "end_at": "2015-03-31 11:24:43.863171", "expect": null, "name": "The3rdTest.testGame"}
{"result": "fail", "start_at": "2015-03-31 11:24:47.633372", "log": "report/2015-03-31_11:21:44.594995/fail/The3rdTest.testYouku@2015-03-31_11:24:47.633372/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 142, in testYouku\n    assert d(textContains = '\u9009\u96c6').wait.exists(timeout = 5000),'Switch surface view failed in 5s!'\n", "AssertionError: Switch surface view failed in 5s!\n"], "screenshot_at_failure": "report/2015-03-31_11:21:44.594995/fail/The3rdTest.testYouku@2015-03-31_11:24:47.633372/failure.png", "end_at": "2015-03-31 11:25:10.307317", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "pass", "start_at": "2015-03-31 11:33:49.976279", "name": "The3rdTest.testWeibo", "end_at": "2015-03-31 11:34:43.795166"}
{"result": "pass", "start_at": "2015-03-31 11:34:43.796428", "name": "The3rdTest.testWeixin", "end_at": "2015-03-31 11:35:14.494212"}
{"result": "pass", "start_at": "2015-03-31 11:35:14.495295", "name": "The3rdTest.testNavigation", "end_at": "2015-03-31 11:35:57.253444"}
{"result": "pass", "start_at": "2015-03-31 11:35:57.254556", "name": "The3rdTest.testGame", "end_at": "2015-03-31 11:56:55.333713"}
{"result": "pass", "start_at": "2015-03-31 11:56:55.334828", "name": "The3rdTest.testYouku", "end_at": "2015-03-31 11:57:35.256874"}
{"result": "error", "start_at": "2015-03-31 11:57:35.257918", "log": "report/2015-03-31_11:33:49.973508/error/The3rdTest.testWeibo@2015-03-31_11:57:35.257918/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 35, in testWeibo\n    d(resourceId = 'com.sina.weibo:id/et_mblog').set_text('Good!')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 792, in set_text\n    return self.jsonrpc.setText(self.selector, text)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[RESOURCE_ID=com.sina.weibo:id/et_mblog]\n"], "screenshot_at_failure": "report/2015-03-31_11:33:49.973508/error/The3rdTest.testWeibo@2015-03-31_11:57:35.257918/failure.png", "end_at": "2015-03-31 11:58:30.125333", "expect": null, "name": "The3rdTest.testWeibo"}
{"result": "pass", "start_at": "2015-03-31 11:58:34.130828", "name": "The3rdTest.testWeixin", "end_at": "2015-03-31 11:59:04.727302"}
{"result": "pass", "start_at": "2015-03-31 11:59:04.728475", "name": "The3rdTest.testNavigation", "end_at": "2015-03-31 11:59:39.198615"}
{"result": "pass", "start_at": "2015-03-31 11:59:39.199798", "name": "The3rdTest.testGame", "end_at": "2015-03-31 12:20:47.817123"}
{"result": "fail", "start_at": "2015-03-31 12:20:47.818267", "log": "report/2015-03-31_11:33:49.973508/fail/The3rdTest.testYouku@2015-03-31_12:20:47.818267/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/the3rd.py\", line 138, in testYouku\n    assert d(resourceId = 'com.youku.phone:id/home_gallery_item_title_layout').wait.exists(timeout = 10000),'Youku homepage does not loading finished in 10s!'\n", "AssertionError: Youku homepage does not loading finished in 10s!\n"], "screenshot_at_failure": "report/2015-03-31_11:33:49.973508/fail/The3rdTest.testYouku@2015-03-31_12:20:47.818267/failure.png", "end_at": "2015-03-31 12:21:11.637548", "expect": null, "name": "The3rdTest.testYouku"}
{"result": "error", "start_at": "2015-03-31 13:15:39.608437", "log": "report/2015-03-31_13:15:31.476251/error/TelephonyTest.testSwitchMobileNetWorkTo2G@2015-03-31_13:15:39.608437/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/telephony.py\", line 73, in testSwitchMobileNetWorkTo2G\n    self._setMobileNetWork('2G')\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/telephony.py\", line 143, in _setMobileNetWork\n    d(text = '\u8702\u7a9d\u79fb\u52a8\u6570\u636e').click.wait()\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 71, in __call__\n    return self.func(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 815, in _click\n    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 416, in wrapper\n    return _method_obj(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py\", line 123, in __call__\n    raise JsonRPCError(jsonresult[\"error\"][\"code\"], jsonresult[\"error\"][\"message\"])\n", "JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[TEXT=\\u8702\\u7a9d\\u79fb\\u52a8\\u6570\\u636e]\n"], "screenshot_at_failure": "report/2015-03-31_13:15:31.476251/error/TelephonyTest.testSwitchMobileNetWorkTo2G@2015-03-31_13:15:39.608437/failure.png", "end_at": "2015-03-31 13:16:14.774444", "expect": null, "name": "TelephonyTest.testSwitchMobileNetWorkTo2G"}
{"result": "fail", "start_at": "2015-03-31 13:27:20.465334", "log": "report/2015-03-31_13:27:20.440840/fail/MessageTest.testSendMMSWithVideo@2015-03-31_13:27:20.465334/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 59, in testSendMMSWithVideo\n    d.click('MMS_Into_RootDir.png')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 218, in click\n    self.__click_image(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 249, in __click_image\n    raise ExpectException(expect_image_path, current_image_path, reason)\n", "ExpectException: \"Fail Reason: The wanted image 'MMS_Into_RootDir.png' not found on screen!\"\n"], "screenshot_at_failure": "report/2015-03-31_13:27:20.440840/fail/MessageTest.testSendMMSWithVideo@2015-03-31_13:27:20.465334/MMS_Into_RootDir.png", "end_at": "2015-03-31 13:27:50.688926", "expect": "report/2015-03-31_13:27:20.440840/fail/MessageTest.testSendMMSWithVideo@2015-03-31_13:27:20.465334/MMS_Into_RootDir_expect.png", "name": "MessageTest.testSendMMSWithVideo"}
{"result": "fail", "start_at": "2015-03-31 13:27:55.070897", "log": "report/2015-03-31_13:27:20.440840/fail/MessageTest.testSendMMSWithVideo@2015-03-31_13:27:55.070897/log.txt", "trace": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/unittest/case.py\", line 327, in run\n    testMethod()\n", "  File \"/home/xiaobowen/Desktop/stabilitytest/script/testcases/message.py\", line 59, in testSendMMSWithVideo\n    d.click('MMS_Into_RootDir.png')\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 218, in click\n    self.__click_image(*args, **kwargs)\n", "  File \"/usr/local/lib/python2.7/dist-packages/uiautomatorplug/android.py\", line 249, in __click_image\n    raise ExpectException(expect_image_path, current_image_path, reason)\n", "ExpectException: \"Fail Reason: The wanted image 'MMS_Into_RootDir.png' not found on screen!\"\n"], "screenshot_at_failure": "report/2015-03-31_13:27:20.440840/fail/MessageTest.testSendMMSWithVideo@2015-03-31_13:27:55.070897/MMS_Into_RootDir.png", "end_at": "2015-03-31 13:28:22.472189", "expect": "report/2015-03-31_13:27:20.440840/fail/MessageTest.testSendMMSWithVideo@2015-03-31_13:27:55.070897/MMS_Into_RootDir_expect.png", "name": "MessageTest.testSendMMSWithVideo"}
